### ISSUE TITLE
replace .ZipComment? [y]es, [n]o, [A]ll, [N]one, [r]ename:  NULL (assuming [N]one)

### ISSUE THREAD

**Issue by nullxx** [Cynostial/applescript-ipasigner#1]
That error comes when I sign an app. It has to replace the files but It can't because of that error

**Comment by Cynostial** [comment]
Kind of a late answer because I have abandoned that project, but I'm working on an update. The issue you've mentioned is indeed very frustrating

**Comment by Cynostial** [comment]
Fixed it!

**Comment by nullxx** [comment]
Does it work completely?

Is there anyway to codesign in linux or windows?

**Comment by nullxx** [comment]
And thanks!!

**Comment by Cynostial** [comment]
Not sure but I'll keep working on it, but as far as I can tell the single IPA sign works fine! And yeah you can codesign on windows, not sure how that works though

**Comment by nullxx** [comment]
Codesign on windows is very interesting.

Thanks anyway. You are doing a good work!
